### ISSUE TITLE
Cannot connect to mongodb

### ISSUE THREAD

**Issue by nahsi** [louis-lau/DuckyAPI#20]
```shell
MONGODB_URL='mongodb://<username>:<password>@mongo-primary.service.consul:27017,mongo-secondary.service.consul:27017/ducky-api?tls=true&tlsCertificateKeyFile=/secrets/certs/bundle.pem&tlsCAFile=/secrets/certs/CA.pem'
```

Other software from wildduck stack connects just fine with similar mongodb url

```[Nest] 12   - 01/14/2022, 5:31:57 PM   [TypeOrmModule] Unable to connect to the database. Retrying (2)... +3168ms
MongoError: database names cannot contain the character '.'
    at Function.create (/usr/local/ducky-api/node_modules/mongodb/lib/core/error.js:57:12)
    at validateDatabaseName (/usr/local/ducky-api/node_modules/mongodb/lib/operations/db_ops.js:344:24)
    at new Db (/usr/local/ducky-api/node_modules/mongodb/lib/db.js:190:3)
    at MongoClient.db (/usr/local/ducky-api/node_modules/mongodb/lib/mongo_client.js:318:14)
    at MigrationExecutor.<anonymous> (/usr/local/ducky-api/node_modules/typeorm/migration/MigrationExecutor.js:470:34)
    at step (/usr/local/ducky-api/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/ducky-api/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at /usr/local/ducky-api/node_modules/typeorm/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/ducky-api/node_modules/typeorm/node_modules/tslib/tslib.js:111:16)```

**Comment by louis-lau** [comment]
This error seems to be coming from the mongodb driver itself. As far as I know that entire string has nothing changed to it and is passed to the mongodb driver as is. Sorry, but I have no solution for you. Are you really sure it's valid?

**Comment by nahsi** [comment]
@louis-lau yep, pretty sure. zone-mta, haraka, wildduck have (almost) same string.

I will try digging into it, enabling all sorts of debug logs etc and will get back if I found anything, in case anyone else has the same issue.

**Comment by nahsi** [comment]
What I managed to find so far is that it works without TLS, i.e. with a string like this:
```shell
MONGODB_URL='mongodb://<username>:<password>@mongo-primary.service.consul:27017,mongo-secondary.service.consul:27017/ducky-api'
```

Dots that it didn't like were from `bundle.pem` and `CA.pem` in URL params. So this is probably a bug.
